int rc_loadMesh(std::string mesh_file)
int rc_loadMeshFromArchive(std::string archive, std::string mesh_file)
void rc_deleteMesh(int mesh_id)
int rc_createMesh()
bool rc_addMeshBuffer(int mesh_id, int vertex_count, double* vertex_data, double* normal_data, double* uv_data, int index_count, double* index_data)

int rc_createMeshActor(int mesh_id)
int rc_createMeshOctreeActor(int mesh_id)
int rc_createCubeActor(double cube_size)
int rc_createSphereActor(double radius)
void rc_deleteActor(int actor_id)

void rc_setGravity3D(double x, double y, double z)
void rc_setActorCollisionShape(int actor_id, int shape_type, double mass)
int rc_getActorCollisionShape(int actor)
void rc_setActorSolid(int actor_id, bool flag)
bool rc_actorIsSolid(int actor_id)
bool rc_getActorCollision(int actor1, int actor2)


//void rc_setActorTexture(int actor, int layer, int image_id)
//void rc_setActorTextureEx(int actor, int material, int layer, int resource_type, int resource_id)
//Uint32 rc_getActorMaterialCount(int actor)
//void rc_setActorMaterialFlag(int actor, int flag, bool flag_value)
//void rc_setActorMaterialFlagEx(int actor, int material, int flag, bool flag_value)
//bool rc_getActorMaterialFlag(int actor, int material, int flag)
//void rc_setActorMaterialType(int actor, int material_type)
//void rc_setActorMaterialTypeEx(int actor, int material, int material_type)
//int rc_getActorMaterialType(int actor, int material)
//void rc_setActorMaterial(int actor, int material_num, int material_id)
//int rc_getActorMaterial(int actor, int material_num)
//int rc_getActorTexture(int actor, int material, int layer)

void rc_setActorPosition(int actor, double x, double y, double z)
void rc_translateActor(int actor, double x, double y, double z)
void rc_translateActorWorld(int actor, double x, double y, double z)
void rc_getActorPosition(int actor, double* x, double* y, double* z)
void rc_setActorScale(int actor, double x, double y, double z)
void rc_scaleActor(int actor, double x, double y, double z)
void rc_getActorScale(int actor, double* x, double* y, double* z)
void rc_setActorRotation(int actor, double x, double y, double z)
void rc_rotateActor(int actor, double x, double y, double z)
void rc_getActorRotation(int actor, double* x, double* y, double* z)
void rc_setActorGravity(int actor, double x, double y, double z)
void rc_getActorGravity(int actor, double* x, double* y, double* z)
void rc_setActorDamping(int actor, double lin_damping, double ang_damping)
double rc_getActorLinearDamping(int actor)
double rc_getActorAngularDamping(int actor)
double rc_getActorLinearSleepThreshold(int actor)
double rc_getActorAngularSleepThreshold(int actor)
void rc_applyActorDamping(int actor, double timeStep)
void rc_setActorMassProperties(int actor, double mass, double inertia_x, double inertia_y, double inertia_z)
void rc_getActorLinearFactor(int actor, double* x, double* y, double* z)
void rc_setActorLinearFactor(int actor, double x, double y, double z)
double rc_getActorInverseMass(int actor)
void rc_integrateActorVelocities(int actor, double step)
void rc_applyActorCentralForceLocal(int actor, double x, double y, double z)
void rc_applyActorCentralForceWorld(int actor, double x, double y, double z)
void rc_getActorTotalForce(int actor, double* x, double* y, double* z)
void rc_getActorTotalTorque(int actor, double* x, double* y, double* z)
void rc_getActorInverseInertiaDiagLocal(int actor, double* x, double* y, double* z)
void rc_setActorInverseInertiaDiagLocal(int actor, double x, double y, double z)
void rc_setActorSleepThresholds(int actor, double linear, double angular)
void rc_applyActorTorqueLocal(int actor, double x, double y, double z)
void rc_applyActorTorqueWorld(int actor, double x, double y, double z)
void rc_applyActorForceLocal(int actor, double x, double y, double z, double rel_x, double rel_y, double rel_z)
void rc_applyActorForceWorld(int actor, double x, double y, double z, double rel_x, double rel_y, double rel_z)
void rc_applyActorCentralImpulseLocal(int actor, double x, double y, double z)
void rc_applyActorCentralImpulseWorld(int actor, double x, double y, double z)
void rc_applyActorTorqueImpulseLocal(int actor, double x, double y, double z)
void rc_applyActorTorqueImpulseWorld(int actor, double x, double y, double z)
void rc_applyActorImpulseLocal(int actor, double x, double y, double z, double rel_x, double rel_y, double rel_z)
void rc_applyActorImpulseWorld(int actor, double x, double y, double z, double rel_x, double rel_y, double rel_z)
void rc_clearActorForces(int actor)
void rc_updateActorInertiaTensor(int actor)
void rc_getActorCOMPosition(int actor, double* x, double* y, double* z)
void rc_getActorRotationQ(int actor, double* x, double* y, double* z, double* w)
void rc_getActorLinearVelocity(int actor, double* x, double* y, double* z)
void rc_getActorAngularVelocity(int actor, double* x, double* y, double* z)
void rc_setActorLinearVelocityLocal(int actor, double x, double y, double z)
void rc_setActorLinearVelocityWorld(int actor, double x, double y, double z)
void rc_setActorAngularVelocityLocal(int actor, double x, double y, double z)
void rc_setActorAngularVelocityWorld(int actor, double x, double y, double z)
void rc_getActorLocalPointVelocity(int actor, double rel_x, double rel_y, double rel_z, double* x, double* y, double* z)
void rc_getActorLinearVelocityLocal(int actor, double* x, double* y, double* z)
void rc_getActorAngularVelocityLocal(int actor, double* x, double* y, double* z)
void rc_getActorAABB(int actor, double* min_x, double* min_y, double* min_z, double* max_x, double* max_y, double* max_z)
double rc_computeActorImpulseDenominator(int actor, double pos_x, double pos_y, double pos_z, double normal_x, double normal_y, double normal_z)
double rc_computeActorAngularImpulseDenominator(int actor, double x, double y, double z)
void rc_setActorAngularFactor(int actor, double x, double y, double z)
void rc_getActorAngularFactor(int actor, double* x, double* y, double* z)
void rc_computeActorGyroImpulseLocal(int actor, double step, double* x, double* y, double* z)
void rc_computeActorGyroImpulseWorld(int actor, double dt, double* x, double* y, double* z)
void rc_getActorLocalInertia(int actor, double* x, double* y, double* z)
int rc_createPointConstraint(int actorA, double pxA, double pyA, double pzA)
int rc_createPointConstraintEx(int actorA, int actorB, double pxA, double pyA, double pzA, double pxB, double pyB, double pzB)
void rc_setConstraintPivotA(int constraint_id, double x, double y, double z)
void rc_setConstraintPivotB(int constraint_id, double x, double y, double z)
int rc_createHingeConstraint(int actorA, double pxA, double pyA, double pzA, double axA, double ayA, double azA)
int rc_createHingeConstraintEx(int actorA,  int actorB, double pxA, double pyA, double pzA, double pxB, double pyB, double pzB,	double axA, double ayA, double azA, double axB, double ayB, double azB)
int rc_createSlideConstraint(int actorA, int frameInB_matrix, bool useLinearReferenceFrameA)
int rc_createSlideConstraintEx(int actorA, int actorB, int frameInA_matrix, int frameInB_matrix, bool useLinearReferenceFrameA)
int rc_createConeConstraint(int actorA, int rbAFrame_matrix)
int rc_createConeConstraintEx(int actorA, int actorB, int rbAFrame_matrix, int rbBFrame_matrix)
void rc_deleteConstraint(int constraint_id)
void rc_getConstraintFrameOffsetA(int constraint_id, double* x, double* y, double* z, double* rx, double* ry, double* rz)
void rc_getConstraintFrameOffsetB(int constraint_id, double* x, double* y, double* z, double* rx, double* ry, double* rz)
void rc_useConstraintFrameOffset(int constraint_id, bool flag)
double rc_getHingeAngle(int constraint_id)
double rc_getHingeAngleEx(int constraint_id, int t_matrixA, int t_matrixB)
double rc_getConstraintBreakingImpulseThreshold(int constraint_id)
int rc_getConstraintAFrame(int constraint_id, int mA)
int rc_getConstraintBFrame(int constraint_id, int mA)
void rc_setConstraintAxis(int constraint_id, double x, double y, double z)
void rc_setConstraintBreakingImpulseThreshold(int constraint_id, double threshold)
void rc_setConstraintFrames(int constraint_id, int frameA_matrix, int frameB_matrix)
void rc_setHingeLimit(int constraint_id, double low, double high, double softness, double bias_factor, double relaxation_factor)
void rc_setConeLimit(int constraint_id, double swingSpan1, double swingSpan2, double twistSpan, double softness, double bias_factor, double relaxation_factor)
double rc_getConstraintLimitBiasFactor(int constraint_id)
double rc_getLimitRelaxationFactor(int constraint_id)
double rc_getConstraintLimitSign(int constraint_id)
int rc_getHingeSolveLimit(int constraint_id)
void rc_useHingeReferenceFrameA(int constraint_id, bool flag)
double rc_getConstraintAppliedImpulse(int constraint_id)
int rc_getConstraintFixedActor(int constraint_id)
void rc_getConstraintPivotA(int constraint_id, double* x, double* y, double* z)
void rc_getConstraintPivotB(int constraint_id, double* x, double* y, double* z)
int rc_getConstraintActorA(int constraint_id)
int rc_getConstraintActorB(int constraint_id)
void rc_setConstraintSolverIterations(int constraint_id, int num)
double rc_getConstraintBiasFactor(int constraint_id)
double rc_getConstraintDamping(int constraint_id)
double rc_getConstraintFixThresh(int constraint_id)
double rc_getConstraintLimit(int constraint_id, int limit_index)
double rc_getConstraintLimitSoftness(int constraint_id)
double rc_getConstraintSolverIterations(int constraint_id)
void rc_getConstraintAnglePoint(int constraint_id, double angle, double len, double* x, double* y, double* z)
bool rc_getConstraintAngularOnly(int constraint_id)
int rc_getConstraintSolveSwingLimit(int constraint_id)
int rc_getConstraintSolveTwistLimit(int constraint_id)
int rc_getConstraintSolveLimit(int constraint_id)
double rc_getConstraintSwingSpan1(int constraint_id)
int rc_getConstraintSwingSpan2(int constraint_id)
double rc_getConstraintTwistAngle(int constraint_id)
double rc_getConstraintTwistLimitSign(int constraint_id)
int rc_getConstraintTwistSpan(int constraint_id)
void rc_setConstraintAngularOnly(int constraint_id, bool flag)
void rc_setConstraintDamping(int constraint_id, double damping)
void rc_setConstraintFixThresh(int constraint_id, double fixThresh)
void rc_getConstraintAnchorA(int constraint_id, double* x, double* y, double* z)
void rc_getConstraintAnchorB(int constraint_id, double* x, double* y, double* z)
double rc_getConstraintAngDepth(int constraint_id)
double rc_getConstraintAngularPos(int constraint_id)
double rc_getConstraintDampingDirAng(int constraint_id)
double rc_getConstraintDampingDirLin(int constraint_id)
double rc_getConstraintDampingLimAng(int constraint_id)
double rc_getConstraintDampingLimLin(int constraint_id)
double rc_getConstraintDampingOrthoAng(int constraint_id)
double rc_getConstraintDampingOrthoLin(int constraint_id)
double rc_getConstraintLinearPos(int constraint_id)
double rc_getConstraintLinDepth(int constraint_id)
double rc_getConstraintLowerAngLimit(int constraint_id)
double rc_getConstraintLowerLinLimit(int constraint_id)
double rc_getConstraintRestitutionDirAng(int constraint_id)
double rc_getConstraintRestitutionDirLin(int constraint_id)
double rc_getConstraintRestitutionLimAng(int constraint_id)
double rc_getConstraintRestitutionLimLin(int constraint_id)
double rc_getConstraintRestitutionOrthoAng(int constraint_id)
double rc_getConstraintRestitutionOrthoLin(int constraint_id)
double rc_getConstraintSoftnessDirAng(int constraint_id)
double rc_getConstraintSoftnessDirLin(int constraint_id)
double rc_getConstraintSoftnessLimAng(int constraint_id)
double rc_getConstraintSoftnessLimLin(int constraint_id)
double rc_getConstraintSoftnessOrthoAng(int constraint_id)
double rc_getConstraintSoftnessOrthoLin(int constraint_id)
bool rc_getConstraintSolveAngLimit(int constraint_id)
bool rc_getConstraintSolveLinLimit(int constraint_id)
double rc_getConstraintUpperAngLimit(int constraint_id)
double rc_getConstraintUpperLinLimit(int constraint_id)
bool rc_getConstraintUseFrameOffset(int constraint_id)
void rc_setConstraintDampingDirAng(int constraint_id, double n)
void rc_setConstraintDampingDirLin(int constraint_id, double n)
void rc_setConstraintDampingLimAng(int constraint_id, double n)
void rc_setConstraintDampingLimLin(int constraint_id, double n)
void rc_setConstraintDampingOrthoAng(int constraint_id, double n)
void rc_setConstraintDampingOrthoLin(int constraint_id, double n)
void rc_setConstraintLowerAngLimit(int constraint_id, double n)
void rc_setConstraintLowerLinLimit(int constraint_id, double n)
void rc_setConstraintRestitutionDirAng(int constraint_id, double n)
void rc_setConstraintRestitutionDirLin(int constraint_id, double n)
void rc_setConstraintRestitutionLimAng(int constraint_id, double n)
void rc_setConstraintRestitutionLimLin(int constraint_id, double n)
void rc_setConstraintRestitutionOrthoAng(int constraint_id, double n)
void rc_setConstraintRestitutionOrthoLin(int constraint_id, double n)
void rc_setConstraintSoftnessDirAng(int constraint_id, double n)
void rc_setConstraintSoftnessDirLin(int constraint_id, double n)
void rc_setConstraintSoftnessLimAng(int constraint_id, double n)
void rc_setConstraintSoftnessLimLin(int constraint_id, double n)
void rc_setConstraintSoftnessOrthoAng(int constraint_id, double n)
void rc_setConstraintSoftnessOrthoLin(int constraint_id, double n)
void rc_setConstraintUpperAngLimit(int constraint_id, double n)
void rc_setConstraintUpperLinLimit(int constraint_id, double n)


void rc_setWorld3DDeltaTime(double dt)
void rc_setWorld3DMaxSubSteps(double steps)
void rc_setWorld3DTimeStep(double ts)




void rc_setActorAnimation(int actor, int start_frame, int end_frame)
void rc_setActorAnimationSpeed(int actor, double speed)

void rc_setCameraPosition(double x, double y, double z)
void rc_getCameraPosition(double* x, double* y, double* z)
void rc_translateCamera(double x, double y, double z)
void rc_translateCameraW(double x, double y, double z)
void rc_setCameraRotation(double x, double y, double z)
void rc_getCameraRotation(double* x, double* y, double* z)
void rc_rotateCamera(double x, double y, double z)
