Function CreateActorAnimation(actor, start_frame, end_frame, speed)
sub SetActorAnimation( actor, animation, num_loops)
sub SetActorAnimationSpeed( actor, animation, speed )
sub SetActorAnimationFrames(actor, animation, start_frame, end_frame)
Function GetActorCurrentAnimation(actor)
function GetActorAnimationSpeed( actor, animation )
Function GetActorAnimationStartFrame(actor, animation)
Function GetActorAnimationEndFrame(actor, animation)
sub SetActorFrame(actor, frame)
function GetActorFrame(actor)
function ActorAnimationIsPlaying(actor)
function NumActorAnimationLoops(actor)
sub SetActorMD2Animation( actor, anim, num_loops )
sub SetActorMD2AnimationByName( actor, anim_name$, num_loops )
sub DeleteActorAnimation(actor, animation)
function GetActorBoneCount( actor )
function GetActorBoneIndex( actor, bone_name$ )
function GetActorBoneName$( actor, bone_index )
function GetActorBonePosition( actor, bone_index, ByRef x, ByRef y, ByRef z )
function GetActorBoneRotation( actor, bone_index, ByRef x, ByRef y, ByRef z )
function GetActorBoneScale( actor, bone_index, ByRef x, ByRef y, ByRef z )
function GetActorBoneRelativeTranform( actor, bone_index, t_matrix )
function GetActorBoneAbsoluteTranform( actor, bone_index, t_matrix )
