sub SetGravity3D(x, y, z)
sub GetGravity3D(ByRef x, ByRef y, ByRef z)
sub SetActorCollisionShape( actor, shape_type, mass)
function GetActorCollisionShape(actor)
sub SetActorSolid(actor, flag)
function ActorIsSolid(actor)
function GetActorCollision(actor1, actor2)
sub SetActorGravity( actor, x, y, z )
sub GetActorGravity( actor, ByRef x, ByRef y, ByRef z )
sub setActorDamping( actor,   lin_damping,   ang_damping)
function getActorLinearDamping( actor)
function  getActorAngularDamping( actor)
function  getActorLinearSleepThreshold( actor)
function  getActorAngularSleepThreshold( actor)
sub applyActorDamping( actor,   timeStep)
sub setActorMassProperties( actor,   mass,   inertia_x,   inertia_y,   inertia_z)
sub getActorLinearFactor( actor,  ByRef  x,  ByRef  y,  ByRef  z)
sub setActorLinearFactor( actor,   x,   y,   z)
function  getActorInverseMass( actor)
sub integrateActorVelocities( actor,  v_step)
sub applyActorCentralForceLocal( actor,   x,   y,   z)
sub applyActorCentralForceWorld( actor,   x,   y,   z)
sub getActorTotalForce( actor,  ByRef  x,  ByRef  y,  ByRef  z)
sub getActorTotalTorque( actor,  ByRef  x,  ByRef  y,  ByRef  z)
sub getActorInverseInertiaDiagLocal( actor,  ByRef  x,  ByRef  y,  ByRef  z)
sub setActorInverseInertiaDiagLocal( actor,   x,   y,   z)
sub setActorSleepThresholds( actor,   linear,   angular)
sub applyActorTorqueLocal( actor,   x,   y,   z)
sub applyActorTorqueWorld( actor,   x,   y,   z)
sub applyActorForceLocal( actor,   x,   y,   z,   rel_x,   rel_y,   rel_z)
sub applyActorForceWorld( actor,   x,   y,   z,   rel_x,   rel_y,   rel_z)
sub applyActorCentralImpulseLocal( actor,   x,   y,   z)
sub applyActorCentralImpulseWorld( actor,   x,   y,   z)
sub applyActorTorqueImpulseLocal( actor,   x,   y,   z)
sub applyActorTorqueImpulseWorld( actor,   x,   y,   z)
sub applyActorImpulseLocal( actor,   x,   y,   z,   rel_x,   rel_y,   rel_z)
sub applyActorImpulseWorld( actor,   x,   y,   z,   rel_x,   rel_y,   rel_z)
sub clearActorForces( actor)
sub updateActorInertiaTensor( actor)
sub getActorCenter( actor,  ByRef  x,  ByRef  y,  ByRef  z)
sub getActorRotationQ( actor,  ByRef  x,  ByRef  y,  ByRef  z,  ByRef  w)
sub getActorLinearVelocityWorld( actor,  ByRef  x,  ByRef  y,  ByRef  z)
sub getActorAngularVelocityWorld( actor,  ByRef  x,  ByRef  y,  ByRef  z)
sub setActorLinearVelocityLocal( actor,   x,   y,   z)
sub setActorLinearVelocityWorld( actor,   x,   y,   z)
sub setActorAngularVelocityLocal( actor,   x,   y,   z)
sub setActorAngularVelocityWorld( actor,   x,   y,   z)
sub getActorVelocityInLocalPoint( actor,   rel_x,   rel_y,   rel_z,  ByRef  x,  ByRef  y,  ByRef  z)
sub getActorLinearVelocityLocal( actor,  ByRef  x,  ByRef  y,  ByRef  z)
sub getActorAngularVelocityLocal( actor,  ByRef  x,  ByRef  y,  ByRef  z)
sub getActorAABB( actor,  ByRef  min_x,  ByRef  min_y,  ByRef  min_z,  ByRef  max_x,  ByRef  max_y,  ByRef  max_z)
function  computeActorImpulseDenominator( actor,   pos_x,   pos_y,   pos_z,   normal_x,   normal_y,   normal_z)
function  computeActorAngularImpulseDenominator( actor,   x,   y,   z)
sub setActorAngularFactor( actor,   x,   y,   z)
sub getActorAngularFactor( actor,  ByRef  x,  ByRef  y,  ByRef  z)
sub computeActorGyroImpulseLocal( actor,   dt,  ByRef  x,  ByRef  y,  ByRef  z)
sub computeActorGyroImpulseWorld( actor,   dt,  ByRef  x,  ByRef  y,  ByRef  z)
sub getActorLocalInertia( actor,  ByRef  x,  ByRef  y,  ByRef  z)
sub SetActorSleepState(actor, state)
function CastRay3D( from_x, from_y, from_z, to_x, to_y, to_z )
function CastRay3D_All( from_x, from_y, from_z, to_x, to_y, to_z )
sub GetRayHit3D( index, ByRef actor_id, ByRef x, ByRef y, ByRef z, ByRef normal_x, ByRef normal_y, ByRef normal_z )
