function CreateMeshActor( mesh )
function CreateMeshOctreeActor( mesh )
function CreateCubeActor( cube_size )
function CreateSphereActor( radius )
sub DeleteActor( actor )
sub GetActorTransform( actor, matrix )
function CreateTerrainActor( hmap_file$ )
sub GetTerrainPatchAABB( actor, patchX, patchZ, ByRef minX, ByRef minY, ByRef minZ, ByRef maxX, ByRef maxY, ByRef maxZ )
function GetTerrainPatchLOD( actor, patchX, patchZ )
function GetTerrainHeight( actor, patchX, patchZ )
sub GetTerrainCenter( actor, ByRef x, ByRef y, ByRef z )
sub SetTerrainLODDistance( actor, LOD, distance )
sub ScaleTerrainTexture( actor, scale, scale2 )
sub SetTerrainCameraMovementDelta( actor, delta )
sub SetTerrainCameraRotationDelta( actor, delta )
sub SetTerrainPatchLOD( actor, patchX, patchZ, LOD )
sub SetActorTexture( actor, layer, image_id )
sub SetActorTextureEx( actor, material, layer, resource_type, resource_id )
function GetActorTexture( actor, material, layer )
function GetActorMaterialCount( actor )
sub SetActorMaterialFlag( actor, flag, flag_value )
sub SetActorMaterialFlagEx( actor, material, flag, flag_value)
function GetActorMaterialFlag( actor, material, flag)
sub SetActorMaterialType( actor, material_type)
sub SetActorMaterialTypeEx( actor, material, material_type)
function GetActorMaterialType( actor, material )
sub SetActorMaterial( actor, material_num, material_id)
function GetActorMaterial( actor, material_num)
sub SetActorPosition( actor, x, y, z )
sub TranslateActor( actor, x, y, z )
sub TranslateActorWorld( actor, x, y, z )
sub GetActorPosition( actor, ByRef x, ByRef y, ByRef z )
sub SetActorScale( actor, x, y, z )
sub ScaleActor( actor, x, y, z )
sub GetActorScale( actor, ByRef x, ByRef y, ByRef z )
sub SetActorRotation( actor, x, y, z )
sub RotateActor( actor, x, y, z )
sub GetActorRotation( actor, ByRef x, ByRef y, ByRef z )
sub SetActorAnimation( actor, start_frame, end_frame)
sub SetActorAnimationSpeed( actor, speed )
sub SetActorFrame( actor, frame )
function SetActorMD2Animation( actor, anim )
function SetActorMD2AnimationByName( actor, anim_name$ )
function GetActorAnimationSpeed( actor )
function GetActorEndFrame( actor )
function GetActorCurrentFrame( actor )
function GetActorStartFrame( actor )
sub SetActorVisible( actor, flag )
function ActorIsVisible( actor )
sub SetActorAutoCulling( actor, cull_type )
function GetActorAutoCulling( actor )
function actorAnimationIsLooped( actor )
sub loopActorAnimation( actor, flag )
sub AddActorShadow( actor )
sub RemoveActorShadow( actor )
sub StartActorTransition( actor, frame, transition_time )
sub StopActorTransition( actor )
function ActorIsInTransition( actor )
function GetActorTransitionTime( actor )
sub SetActorAnimation( actor, start_frame, end_frame)
sub SetActorAnimationSpeed( actor, speed )
sub SetActorFrame( actor, frame )
sub SetActorJointMode( actor, mode )
sub SetActorLoopMode( actor, mode )
function SetActorMD2Animation( actor, anim )
function SetActorMD2AnimationByName( actor, anim_name$ )
sub SetActorMesh( actor, mesh )
sub SetActorRenderFromIdentity( actor, flag )
sub SetActorTransitionTime( actor )
function GetActorLoopMode( actor )
function GetActorAnimationSpeed( actor )
function GetActorEndFrame( actor )
function GetActorCurrentFrame( actor )
function GetActorStartFrame( actor )
sub SetActorVisible( actor, flag )
function GetActorVisible( actor )
