sub SetActorAnimation( actor, start_frame, end_frame)
sub SetActorAnimationSpeed( actor, speed )
sub SetActorFrame( actor, frame )
sub SetActorMD2Animation( actor, anim )
sub SetActorMD2AnimationByName( actor, anim_name$ )
function GetActorAnimationSpeed( actor )
function GetActorEndFrame( actor )
function GetActorCurrentFrame( actor )
function GetActorStartFrame( actor )
sub StartActorTransition( actor, frame, transition_time )
sub StopActorTransition( actor )
function ActorIsInTransition( actor )
function GetActorTransitionTime( actor )
function actorAnimationIsLooped( actor )
sub loopActorAnimation( actor, flag )
