sub SetCameraPosition( x, y, z)
sub GetCameraPosition(ByRef x, ByRef y, ByRef z)
sub TranslateCamera( x, y, z)
sub SetCameraRotation( x, y, z)
sub GetCameraRotation(ByRef x, ByRef y, ByRef z)
sub RotateCamera( x, y, z)
