Function AddCompositeChild(actor, child_actor, t_matrix)
Function GetCompositeChildCount(actor)
Function GetCompositeChild(actor, child_index)
Function GetCompositeChildIndex(actor, child_actor)
Sub RemoveCompositeChild(actor, child_index)
Function GetCompositeChildTransform(actor, child_index, t_matrix)
Function GetCompositeAABB(actor, t_matrix, ByRef min_x, ByRef min_y, ByRef min_z, ByRef max_x, ByRef max_y, ByRef max_z)
Sub RecalculateCompositeAABB(actor)
Sub GenerateCompositeAABBFromChildren(actor)
Sub CalculateCompositePrincipalTransform(actor, ByRef masses, principal_matrix, ByRef x, ByRef y, ByRef z)
Sub UpdateCompositeChildTransform(actor, child_index, t_matrix, recalc_flag)
Function GetCompositeUpdateRevision(actor)
