function  createPointConstraint( actorA,  pxA,  pyA,  pzA)
function  createPointConstraintEx( actorA,  actorB,  pxA,  pyA,  pzA,  pxB,  pyB,  pzB)
sub  setConstraintPivotA( constraint_id,  x,  y,  z)
sub  setConstraintPivotB( constraint_id,  x,  y,  z)
function  createHingeConstraint( actorA,  pxA,  pyA,  pzA,  axA,  ayA,  azA)
function  createHingeConstraintEx( actorA,   actorB,  pxA,  pyA,  pzA,  pxB,  pyB,  pzB,
function  createSlideConstraint( actorA,  frameInB_matrix,  useLinearReferenceFrameA)
function  createSlideConstraintEx( actorA,  actorB,  frameInA_matrix,  frameInB_matrix,  useLinearReferenceFrameA)
function  createConeConstraint( actorA,  rbAFrame_matrix)
function  createConeConstraintEx( actorA,  actorB,  rbAFrame_matrix,  rbBFrame_matrix)
sub  deleteConstraint( constraint_id)
sub  getConstraintFrameOffsetA( constraint_id, ByRef x, ByRef y, ByRef z, ByRef rx, ByRef ry, ByRef rz)
sub  getConstraintFrameOffsetB( constraint_id, ByRef x, ByRef y, ByRef z, ByRef rx, ByRef ry, ByRef rz)
sub  useConstraintFrameOffset( constraint_id,  flag)
function  getHingeAngle( constraint_id)
function  getHingeAngleEx( constraint_id,  t_matrixA,  t_matrixB)
function  getConstraintBreakingImpulseThreshold( constraint_id)
function  getConstraintAFrame( constraint_id,  mA)
function  getConstraintBFrame( constraint_id,  mA)
sub  setConstraintAxis( constraint_id,  x,  y,  z)
sub  setConstraintBreakingImpulseThreshold( constraint_id,  threshold)
sub  setConstraintFrames( constraint_id,  frameA_matrix,  frameB_matrix)
sub  setHingeLimit( constraint_id,  low,  high,  softness,  bias_factor,  relaxation_factor)
sub  setConeLimit( constraint_id,  swingSpan1,  swingSpan2,  twistSpan,  softness,  bias_factor,  relaxation_factor)
function  getConstraintLimitBiasFactor( constraint_id)
function  getLimitRelaxationFactor( constraint_id)
function  getConstraintLimitSign( constraint_id)
function  getHingeSolveLimit( constraint_id)
sub  useHingeReferenceFrameA( constraint_id,  flag)
function  getConstraintAppliedImpulse( constraint_id)
function  getConstraintFixedActor( constraint_id)
sub  getConstraintPivotA( constraint_id, ByRef x, ByRef y, ByRef z)
sub  getConstraintPivotB( constraint_id, ByRef x, ByRef y, ByRef z)
function  getConstraintActorA( constraint_id)
function  getConstraintActorB( constraint_id)
sub  setConstraintSolverIterations( constraint_id,  num)
function  getConstraintBiasFactor( constraint_id)
function  getConstraintDamping( constraint_id)
function  getConstraintFixThresh( constraint_id)
function  getConstraintLimit( constraint_id,  limit_index)
function  getConstraintLimitSoftness( constraint_id)
function  getConstraintSolverIterations( constraint_id)
sub  getConstraintAnglePoint( constraint_id,  angle,  len, ByRef x, ByRef y, ByRef z)
function  getConstraintAngularOnly( constraint_id)
function  getConstraintSolveSwingLimit( constraint_id)
function  getConstraintSolveTwistLimit( constraint_id)
function  getConstraintSolveLimit( constraint_id)
function  getConstraintSwingSpan1( constraint_id)
function  getConstraintSwingSpan2( constraint_id)
function  getConstraintTwistAngle( constraint_id)
function  getConstraintTwistLimitSign( constraint_id)
function  getConstraintTwistSpan( constraint_id)
sub  setConstraintAngularOnly( constraint_id,  flag)
sub  setConstraintDamping( constraint_id,  damping)
sub  setConstraintFixThresh( constraint_id,  fixThresh)
sub  getConstraintAnchorA( constraint_id, ByRef x, ByRef y, ByRef z)
sub  getConstraintAnchorB( constraint_id, ByRef x, ByRef y, ByRef z)
function  getConstraintAngDepth( constraint_id)
function  getConstraintAngularPos( constraint_id)
function  getConstraintDampingDirAng( constraint_id)
function  getConstraintDampingDirLin( constraint_id)
function  getConstraintDampingLimAng( constraint_id)
function  getConstraintDampingLimLin( constraint_id)
function  getConstraintDampingOrthoAng( constraint_id)
function  getConstraintDampingOrthoLin( constraint_id)
function  getConstraintLinearPos( constraint_id)
function  getConstraintLinDepth( constraint_id)
function  getConstraintLowerAngLimit( constraint_id)
function  getConstraintLowerLinLimit( constraint_id)
function  getConstraintRestitutionDirAng( constraint_id)
function  getConstraintRestitutionDirLin( constraint_id)
function  getConstraintRestitutionLimAng( constraint_id)
function  getConstraintRestitutionLimLin( constraint_id)
function  getConstraintRestitutionOrthoAng( constraint_id)
function  getConstraintRestitutionOrthoLin( constraint_id)
function  getConstraintSoftnessDirAng( constraint_id)
function  getConstraintSoftnessDirLin( constraint_id)
function  getConstraintSoftnessLimAng( constraint_id)
function  getConstraintSoftnessLimLin( constraint_id)
function  getConstraintSoftnessOrthoAng( constraint_id)
function  getConstraintSoftnessOrthoLin( constraint_id)
function  getConstraintSolveAngLimit( constraint_id)
function  getConstraintSolveLinLimit( constraint_id)
function  getConstraintUpperAngLimit( constraint_id)
function  getConstraintUpperLinLimit( constraint_id)
function  getConstraintUseFrameOffset( constraint_id)
sub  setConstraintDampingDirAng( constraint_id,  n)
sub  setConstraintDampingDirLin( constraint_id,  n)
sub  setConstraintDampingLimAng( constraint_id,  n)
sub  setConstraintDampingLimLin( constraint_id,  n)
sub  setConstraintDampingOrthoAng( constraint_id,  n)
sub  setConstraintDampingOrthoLin( constraint_id,  n)
sub  setConstraintLowerAngLimit( constraint_id,  n)
sub  setConstraintLowerLinLimit( constraint_id,  n)
sub  setConstraintRestitutionDirAng( constraint_id,  n)
sub  setConstraintRestitutionDirLin( constraint_id,  n)
sub  setConstraintRestitutionLimAng( constraint_id,  n)
sub  setConstraintRestitutionLimLin( constraint_id,  n)
sub  setConstraintRestitutionOrthoAng( constraint_id,  n)
sub  setConstraintRestitutionOrthoLin( constraint_id,  n)
sub  setConstraintSoftnessDirAng( constraint_id,  n)
sub  setConstraintSoftnessDirLin( constraint_id,  n)
sub  setConstraintSoftnessLimAng( constraint_id,  n)
sub  setConstraintSoftnessLimLin( constraint_id,  n)
sub  setConstraintSoftnessOrthoAng( constraint_id,  n)
sub  setConstraintSoftnessOrthoLin( constraint_id,  n)
sub  setConstraintUpperAngLimit( constraint_id,  n)
sub  setConstraintUpperLinLimit( constraint_id,  n)
