function LoadImage( img$ )
sub LoadImage_Ex(slot, img$, colkey)
function createImage(w, h, byref buffer)
function createImageEx(w, h, byref buffer, color)
sub getImageBuffer(img_id, byref buffer)
function ImageExists(slot)
sub ColorKey(slot, c)
sub setBilinearFilter( flag )
function getBilinearFilter()
function CopyImage( img_id )
sub DeleteImage(slot)
sub SetImageAlpha(slot, a)
function getImageAlpha( img_id )
sub GetImageSize(slot, byref w, byref h)
sub SetBlendMode( blend_mode )
function getBlendMode( blend_mode )
function SetImageColorMod(slot, c)
function ImageColorMod(slot)
sub DrawImage(slot, x, y)
sub DrawImage_Blit(slot, x, y, src_x, src_y, src_w, src_h)
sub DrawImage_Blit_Ex(slot, x, y, w, h, src_x, src_y, src_w, src_h)
sub DrawImage_Rotate(slot, x, y, angle)
sub DrawImage_Rotate_Ex(slot, x, y, src_x, src_y, src_w, src_h, angle)
sub DrawImage_Zoom(slot, x, y, zx, zy)
sub DrawImage_Zoom_Ex(slot, x, y, src_x, src_y, src_w, src_h, zx, zy)
sub DrawImage_Rotozoom(slot, x, y, angle, zx, zy)
sub DrawImage_Rotozoom_Ex(slot, x, y, src_x, src_y, src_w, src_h, angle, zx, zy)
sub DrawImage_Flip(slot, x, y, h, v)
sub DrawImage_Flip_Ex(slot, x, y, src_x, src_y, src_w, src_h, h, v)
function DrawGeometry(slot, num_vertices, ByRef vertices, num_indices, ByRef Indices)
function SaveBMP(img, file$)
function SavePNG(img, file$)
function SaveJPG(img, file$)
