function LoadImage( img$ )
function LoadImageEx(img$, colkey)
function createImage(w, h, byref buffer)
function createImageEx(w, h, byref buffer, color)
sub getImageBuffer(img_id, byref buffer)
function ImageExists(slot)
sub ColorKey(slot, c)
sub setBilinearFilter( flag )
function getBilinearFilter()
function CopyImage( img_id )
sub DeleteImage(slot)
sub SetImageAlpha(slot, a)
function GetImageAlpha( img_id )
sub GetImageSize(slot, byref w, byref h)
sub SetBlendMode( blend_mode )
function GetBlendMode( )
sub SetImageColorMod(slot, c)
function GetImageColorMod(slot)
sub DrawImage(slot, x, y)
sub DrawImage_Blit(slot, x, y, src_x, src_y, src_w, src_h)
sub DrawImage_BlitEx(slot, x, y, w, h, src_x, src_y, src_w, src_h)
sub DrawImage_Rotate(slot, x, y, angle)
sub DrawImage_RotateEx(slot, x, y, src_x, src_y, src_w, src_h, angle)
sub DrawImage_Zoom(slot, x, y, zx, zy)
sub DrawImage_ZoomEx(slot, x, y, src_x, src_y, src_w, src_h, zx, zy)
sub DrawImage_Rotozoom(slot, x, y, angle, zx, zy)
sub DrawImage_RotozoomEx(slot, x, y, src_x, src_y, src_w, src_h, angle, zx, zy)
sub DrawImage_Flip(slot, x, y, h, v)
sub DrawImage_FlipEx(slot, x, y, src_x, src_y, src_w, src_h, h, v)
