function createDistanceJoint( spriteA,  spriteB,   aX,   aY,   bX,   bY)
function createFrictionJoint( spriteA,  spriteB,   x,   y)
function createGearJoint( jointA,  jointB,   g_ratio)
function createMotorJoint( spriteA,  spriteB)
function createPrismaticJoint( spriteA,  spriteB,   aX,   aY,   axisX,   axisY)
function createPulleyJoint( spriteA,  spriteB,   gaX,   gaY,   gbX,   gbY,   aX,   aY,   bX,   bY,   j_ratio)
function createRevoluteJoint( spriteA,  spriteB,   x,   y)
function createWeldJoint( spriteA,  spriteB,   x,   y)
function createWheelJoint( spriteA,  spriteB,   aX,   aY,   axisX,   axisY)
sub getJointWorldAnchorA( joint_id,  ByRef  x,  ByRef  y)
sub getJointWorldAnchorB( joint_id,  ByRef  x,  ByRef  y)
sub getJointReactionForce( joint_id,   inv_dt,  ByRef  x,  ByRef  y)
function  getJointReactionTorque( joint_id,   inv_dt)
sub getJointLocalAnchorA( joint_id,  ByRef  x,  ByRef  y)
sub getJointLocalAnchorB( joint_id,  ByRef  x,  ByRef  y)
sub setJointLength( joint_id,   jlen)
function  getJointLength( joint_id)
sub setJointMinLength( joint_id,   jlen)
function  getJointMinLength( joint_id)
sub setJointMaxLength( joint_id,   jlen)
function  getJointMaxLength( joint_id)
function  getJointCurrentLength( joint_id)
sub setJointStiffness( joint_id,   stiffness)
function  getJointStiffness( joint_id)
sub setJointDamping( joint_id,   damping)
function  getJointDamping( joint_id)
sub setJointMaxForce( joint_id,   force)
function  getJointMaxForce( joint_id)
sub setJointMaxTorque( joint_id,   torque)
function  getJointMaxTorque( joint_id)
sub setJointCorrectionFactor( joint_id,   factor)
function  getJointCorrectionFactor( joint_id)
sub setJointRatio( joint_id,   j_ratio)
function  getJointRatio( joint_id)
sub setJointLinearOffset( joint_id,   x,   y)
sub getJointLinearOffset( joint_id,  ByRef  x,  ByRef  y)
sub setJointAngularOffset( joint_id,   angleOffset)
function  getJointAngularOffset( joint_id)
sub getJointLocalAxisA( joint_id,  ByRef  x,  ByRef  y)
function  getJointReferenceAngle( joint_id)
function  getJointTranslation( joint_id)
function  getJointSpeed( joint_id)
function jointIsLimitEnabled( joint_id)
sub enableJointLimit( joint_id,  flag)
function  getJointLowerLimit( joint_id)
function  getJointUpperLimit( joint_id)
sub setJointLimits( joint_id,   lower_limit,   upper_limit)
function jointMotorIsEnabled( joint_id)
sub enableJointMotor( joint_id,  flag)
sub setJointMotorSpeed( joint_id,   speed)
function  getJointMotorSpeed( joint_id)
sub setJointMaxMotorForce( joint_id,   force)
function  getJointMaxMotorForce( joint_id)
function  getJointMotorForce( joint_id,   inv_dt)
sub setJointMaxMotorTorque( joint_id,   torque)
function  getJointMaxMotorTorque( joint_id)
function  getJointMotorTorque( joint_id,   inv_dt)
sub getJointGroundAnchorA( joint_id,  ByRef  x,  ByRef  y)
sub getJointGroundAnchorB( joint_id,  ByRef  x,  ByRef  y)
function  getJointLengthA( joint_id)
function  getJointLengthB( joint_id)
function  getJointCurrentLengthA( joint_id)
function  getJointCurrentLengthB( joint_id)
sub setJointOrigin( joint_id,   x,   y)
function  getJointAngle( joint_id)
function  getJointLinearSpeed( joint_id)
function  getJointAngularSpeed( joint_id)
