function lightIsCastingShadow( actor )
function getLightType( actor )
function getLightRadius( actor )
sub setLightType( actor, light_type )
sub setLightRadius( actor, radius )
sub setLightShadowCast( actor, flag )
sub SetLightAmbientColor( actor, color )
function GetLightAmbientColor( actor )
sub SetLightAttenuation( actor, l_constant, l_linear, l_quadratic )
sub GetLightAttenuation( actor, ByRef constant, ByRef linear, ByRef quadratic)
sub SetLightDiffuseColor( actor, color )
function GetLightDiffuseColor( actor )
sub SetLightFalloff( actor, falloff )
function GetLightFalloff( actor )
sub SetLightInnerCone( actor, angle )
function GetLightInnerCone( actor )
sub SetLightOuterCone( actor, angle)
function GetLightOuterCone( actor )
sub SetLightSpecularColor( actor, color )
function GetLightSpecularColor( actor )
