function  createMaterial()
sub  deleteMaterial( material_id)
sub  setActorMaterial( actor,  material_num,  material_id)
function  getActorMaterial( actor,  material_num)
function  copyActorMaterial( actor,  material_num)
function  copyMaterial( smaterial_id)
sub  setMaterialTextureCanvas( material_id,  level,  canvas_id)
sub  setMaterialAmbientColor( material_id,  color)
function  getMaterialAmbientColor( material_id)
sub  setMaterialAntiAliasing( material_id,  aa)
function  getMaterialAntiAliasing( material_id)
sub  setMaterialBackfaceCulling( material_id,  flag)
function  getMaterialBackfaceCulling( material_id)
sub  setMaterialBlendFactor( material_id,  bf)
function  getMaterialBlendFactor( material_id)
sub  setMaterialBlendMode( material_id,  blend_mode)
function  getMaterialBlendMode( material_id)
sub  setMaterialColorMask( material_id,  color_mask)
function  getMaterialColorMask( material_id)
sub  setMaterialColorMode( material_id,  color_mode)
function  getMaterialColorMode( material_id)
sub  setMaterialDiffuseColor( material_id,  color)
function  getMaterialDiffuseColor( material_id)
sub  setMaterialEmissiveColor( material_id,  color)
function  getMaterialEmissiveColor( material_id)
sub  setMaterialFog( material_id,  flag)
function  getMaterialFog( material_id)
sub  setMaterialFrontfaceCulling( material_id,  flag)
function  getMaterialFrontfaceCulling( material_id)
sub  setMaterialGouraudShading( material_id,  flag)
function  materialIsGouraudShaded( material_id)
function  materialIsAplhaBlend( material_id)
function  materialIsTransparent( material_id)
sub  setMaterialLighting( material_id,  flag)
function  materialIsLit( material_id)
sub  setMaterialType( material_id,  mat_type)
function  getMaterialType( material_id)
sub  setMaterialNormalize( material_id,  flag)
function  materialIsNormalized( material_id)
sub  setMaterialPointCloud( material_id,  flag)
function  materialIsPointCloud( material_id)
sub  setMaterialFlag( material_id,  material_flag,  f_value)
function  getMaterialFlag( material_id,  material_flag)
sub  setMaterialTexture( material_id,  level,  img_id)
sub  setMaterialShininess( material_id,  shininess)
function  getMaterialShininess( material_id)
sub  setMaterialSpecularColor( material_id,  color)
function  getMaterialSpecularColor( material_id)
sub  setMaterialThickness( material_id,  thickness)
function  getMaterialThickness( material_id)
sub  setMaterialWireframe( material_id,  flag)
function  materialIsWireframe( material_id)
sub  setActorTexture( actor,  layer,  image_id)
function  getActorMaterialCount( actor)
sub  setActorMaterialFlag( actor,  flag,  flag_value)
function  getActorMaterialFlag( actor,  material,  flag)
sub  setActorMaterialType( actor,  material_type)
function  getActorMaterialType( actor,  material)
