function LoadMesh( mesh_file$ )
sub DeleteMesh( mesh )
function CreateMesh( )
sub AddMeshBuffer( mesh, vertex_count, ByRef vertex_data, ByRef normal_data, ByRef uv_data, index_count, ByRef index_data )
function LoadMeshFromArchive( archive$, mesh_file$ )
Function CreatePlaneMesh( w, h, tileCount_w, tileCount_h, txRepeat_x, txRepeat_y )
Function LoadAN8( an8_file$ )
Function LoadMeshFromAN8(an8_project, an8_scene$)
Function GetNumAN8Scenes(an8_project)
Function GetAN8SceneName$(an8_project, scene_num)
Function CreateConeMesh( radius, cone_length, tesselation, top_color, bottom_color )
Function CreateCylinderMesh( radius, cylinder_length, tesselation, color, close_top )
Function CreateVolumeLightMesh( u, v, foot_color, tail_color, lp_distance, dim_x, dim_y, dim_z )
Sub DeleteAN8( an8_project )
