function LoadMesh( mesh_file$ )
sub DeleteMesh( mesh )
function CreateMesh( )
sub AddMeshBuffer( mesh, vertex_count, ByRef vertex_data, ByRef normal_data, ByRef uv_data, index_count, ByRef index_data )
function LoadMeshFromArchive( archive$, mesh_file$ )
Function CreatePlaneMesh( w, h, tileCount_w, tileCount_h )
Function LoadAN8( an8_file$ )
Function LoadMeshFromAN8(an8_project, an8_scene$)
Function GetNumAN8Scenes(an8_project)
Function GetAN8SceneName$(an8_project, scene_num)
