function CheckSockets(timeout_ms)
function TCP_SocketReady(socket)
function UDP_SocketReady(socket)
function TCP_OpenSocket(host$, port)
sub TCP_CloseSocket(socket)
function TCP_RemoteHost(socket)
function TCP_RemotePort(socket)
function TCP_GetData(socket, numBytes, ByRef sData$)
sub TCP_SendData(socket, sData$)
function TCP_AcceptSocket(server, client)
function UDP_OpenSocket(port)
sub UDP_CloseSocket(socket)
function UDP_GetData(socket, byref host$, byref port, byref sData$)
function UDP_Length()
function UDP_MaxLength()
function UDP_RemoteHost$(socket)
function UDP_RemotePort(socket)
sub UDP_SendData(socket, host$, port, sData$)
