sub  startParticleEmitter( actor)
sub  stopParticleEmitter( actor)
sub  setParticleDirection( actor,  x,  y,  z)
sub  getParticleDirection( actor, ByRef x, ByRef y, ByRef z)
sub  useParticleEveryMeshVertex( actor,  flag)
function  particleIsUsingEveryMeshVertex( actor)
sub  setParticleNormalDirectionMod( actor,  nd_mod)
function  getParticleNormalDirectionMod( actor)
sub  useParticleNormalDirection( actor,  flag)
function  particleIsUsingNormalDirection( actor)
sub  setParticleMesh( actor,  mesh)
sub  setParticleMinParticlesPerSecond( actor,  minParticlesPerSecond)
function  getParticleMinParticlesPerSecond( actor)
sub  setParticleMaxParticlesPerSecond( actor,  maxParticlesPerSecond)
function  getParticleMaxParticlesPerSecond( actor)
sub  setParticleMinStartColor( actor,  color)
function  getParticleMinStartColor( actor)
sub  setParticleMaxStartColor( actor,  color)
function  getParticleMaxStartColor( actor)
sub  setParticleMinLife( actor,  minLife)
function  getParticleMinLife( actor)
sub  setParticleMaxLife( actor,  maxLife)
function  getParticleMaxLife( actor)
sub  setParticleMaxAngle( actor,  maxAngle)
function  getParticleMaxAngle( actor)
sub  setParticleMinStartSize( actor,  w,  h)
sub  getParticleMinStartSize( actor, ByRef w, ByRef h)
sub  setParticleMaxStartSize( actor,  w,  h)
sub  getParticleMaxStartSize( actor, ByRef w, ByRef h)
sub  setParticleCenter( actor,  x,  y,  z)
sub  getParticleCenter( actor, ByRef x, ByRef y, ByRef z)
sub  setParticleRadius( actor,  radius)
function  getParticleRadius( actor)
sub  setParticleRingThickness( actor,  ringThickness)
function  getParticleRingThickness( actor)
sub  setParticleBox( actor,  min_x,  min_y,  min_z,  max_x,  max_y,  max_z)
sub  getParticleBox( actor, ByRef min_x, ByRef min_y, ByRef min_z, ByRef max_x, ByRef max_y, ByRef max_z)
sub  setParticleNormal( actor,  x,  y,  z)
sub  getParticleNormal( actor, ByRef x, ByRef y, ByRef z)
sub  setParticleLength( actor,  p_len)
function  getParticleLength( actor)
sub  useParticleOutlineOnly( actor,  flag)
function  particleIsUsingOutlineOnly( actor)
