sub Circle(x,y,radius)
sub CircleFill(x,y,radius)
sub Ellipse(x,y,rx,ry)
sub EllipseFill(x,y,rx,ry)
sub FloodFill(x,y)
function GetPixel(x,y)
sub SetColor(c)
sub Line(x1, y1, x2, y2)
sub Poly(n, byref x, byref y)
sub Rect(x, y, w, h)
sub RectFill(x, y, w, h)
function RGB(r,g,b)
function RGBA(r,g,b,a)
sub Pset(x,y)
