Sub SetProjectorTarget(actor, x, y, z)
Sub GetProjectorTarget(actor, ByRef x, ByRef y, ByRef z)
Sub SetProjectorFOV(actor, fov)
Function GetProjectorFOV(actor)
Sub SetProjectorTexture(actor, img_id)
Function GetProjectorTexture(actor)
Function AddProjectorEffectActor(actor, tgt_actor)
Function GetProjectorEffectActorCount(actor)
Function GetProjectorEffectActor(actor, tgt_index)
Sub RemoveProjectorEffectActor(actor, tgt_index)
