sub AddSceneSkyBox( img_top, img_bottom, img_left, img_right, img_front, img_back)
sub AddSceneSkyDome( img )
sub AddSceneSkyDomeEx( img, horiRes, vertRes, txPercentage, spherePercentage, radius)
sub RemoveSceneSky( )
sub SetWorld3DMaxSubSteps( steps )
sub SetWorld3DTimeStep( ts )
function GetWorld3DMaxSubSteps()
function GetWorld3DTimeStep()
