Function CreateSpriteAnimation(sprite, anim_length, speed)
Sub SetSpriteFrame(sprite, frame)
Function GetSpriteFrame(sprite)
Sub SetSpriteAnimationFrame(sprite, animation, anim_frame, frame)
Function GetSpriteAnimationFrame(sprite, animation, anim_frame)
Sub SetSpriteAnimationLength(sprite, animation, anim_length)
Function GetSpriteAnimationLength(sprite, animation)
Sub SetSpriteAnimationSpeed(sprite, animation, speed)
Function GetSpriteAnimationSpeed(sprite, animation)
Sub SetSpriteAnimation(sprite, animation, num_loops)
Function GetSpriteAnimation(sprite)
Function GetSpriteCurrentAnimationFrame(sprite)
Function NumSpriteAnimationLoops(sprite)
Function SpriteAnimationIsPlaying(sprite)
Sub DeleteSpriteAnimation(sprite, animation)
