function CreateSprite( img, frame_w, frame_h )
Sub DeleteSprite( sprite )
Sub SetSpritePosition( sprite, x, y )
Sub TranslateSprite(sprite, x, y)
Sub GetSpritePosition(sprite, ByRef x, ByRef y)
Function SpriteX(sprite)
Function SpriteY(sprite)
Sub SetSpriteRotation(sprite, angle)
Sub RotateSprite(sprite, angle)
Function GetSpriteRotation(sprite)
Sub SetSpriteScale(sprite, x, y)
Sub ScaleSprite(sprite, x, y)
Sub GetSpriteScale(sprite, ByRef x, ByRef y)
Sub SetSpriteZ(sprite, z)
Function SpriteZ(sprite)
Sub GetSpriteSize(sprite, ByRef w, ByRef h)
Function SpriteWidth(sprite)
Function SpriteHeight(sprite)
Sub SetSpriteVisible(sprite, flag)
Function SpriteIsVisible(sprite)
Sub SetSpriteSolid(sprite, flag)
Function SpriteIsSolid(sprite)
Sub SetSpriteType(sprite, sprite_type)
Function GetSpriteType(sprite)
Sub SetSpriteSource(sprite, img)
Function GetSpriteSource(sprite)
