sub getSpriteCenter( spr_id,  ByRef  x,  ByRef  y)
sub setSpriteLinearVelocity( spr_id,   x,   y)
sub getSpriteLinearVelocity( spr_id,  ByRef  x,  ByRef  y)
sub setSpriteAngularVelocity( spr_id,   av)
function  getSpriteAngularVelocity( spr_id)
sub applySpriteForce( spr_id,   fX,   fY,   pX,   pY)
sub applySpriteCentralForce( spr_id,   x,   y)
sub applySpriteTorque( spr_id,   torque)
sub applySpriteLinearImpulse( spr_id,   iX,   iY,   pX,   pY)
sub applySpriteAngularImpulse( spr_id,   impulse)
function  getSpriteMass( spr_id)
function  getSpriteInertia( spr_id)
sub getSpriteWorldPoint( spr_id,   lX,   lY,  ByRef  x,  ByRef  y)
sub getSpriteWorldVector( spr_id,   lX,   lY,  ByRef  x,  ByRef  y)
sub getSpriteLocalPoint( spr_id,   wX,   wY,  ByRef  x,  ByRef  y)
sub getSpriteLocalVector( spr_id,   wX,   wY,  ByRef  x,  ByRef  y)
sub getSpriteLinearVelocityFromLocalPoint( spr_id,   pX,   pY,  ByRef  x,  ByRef  y)
sub getSpriteLinearVelocityFromWorldPoint( spr_id,   wX,   wY,  ByRef  x,  ByRef  y)
function  getSpriteLinearDamping( spr_id)
sub setSpriteLinearDamping( spr_id,   linearDamping)
function  getSpriteAngularDamping( spr_id)
sub setSpriteAngularDamping( spr_id,   angularDamping)
function  getSpriteGravityScale( spr_id)
sub setSpriteGravityScale( spr_id,   g_scale)
sub setSpriteBullet( spr_id,  flag)
function spriteIsBullet( spr_id)
sub setSpriteSleepAllowed( spr_id,  flag)
function spriteSleepAllowed( spr_id)
sub setSpriteAwake( spr_id,  flag)
function spriteIsAwake( spr_id)
sub setSpriteFixedRotation( spr_id,  flag)
function spriteIsFixedRotation( spr_id)
sub SetSpriteDensity( spr_id, density )
function GetSpriteDensity( spr_id )
sub SetSpriteFriction( spr_id, friction )
function GetSpriteFriction( spr_id )
sub SetSpriteRestitution( spr_id, restitution )
function GetSpriteRestitution( spr_id )
sub SetSpriteRestitutionThreshold( spr_id, threshold )
function GetSpriteRestitutionThreshold( spr_id )
sub GetSpriteAABB( spr_id, ByRef x1, ByRef y1, ByRef x2, ByRef y2 )
sub SetGravity2D( x, y )
sub GetGravity2D( ByRef x, ByRef y )
sub SetWorld2DTimeStep( ts )
sub SetWorld2DVelocityIterations( v )
sub SetWorld2DPositionIterations( p )
function GetWorld2DTimeStep()
function GetWorld2DVelocityIterations()
function GetWorld2DPositionIterations()
sub SetWorld2DAutoClearForces( flag )
function GetWorld2DAutoClearForces()
