function CreateStack_N( )
function CreateStack_S()
sub ClearStack_N( num_stack )
sub ClearStack_S( str_stack )
sub DeleteStack_N( num_stack )
sub DeleteStack_S( str_stack )
sub Push_N( num_stack, n )
function Pop_N( num_stack )
sub Push_S( str_stack, s$ )
function Pop_S$( str_stack )
function Stack_Size_N( num_stack )
function Stack_Size_S( str_stack )
