function CreateStack_N( )
function CreateStack_S()
sub ClearStack_N()
sub ClearStack_S()
sub DeleteStack_N( stack_id )
sub DeleteStack_S( stack_id )
sub Stack_N(n)
sub Stack_S(n)
sub Push_N(n)
function Pop_N()
sub Push_S(s$)
function Pop_S$()
function Stack_Size_N()
function Stack_Size_S()
