function System(cmd$)
function OS$()
function Command$(arg)
function NumCommands()
function Env$(v$)
sub SetEnv(var$, value$, overwrite)
function PrefPath$(org_name$, app_name$)
function Android_GetExternalStoragePath$()
function Android_GetExternalStorageState()
function Android_GetInternalStoragePath$()
function Android_JNI_Message$(arg$)
function Runtime_Utility_Message$(arg$)
Sub GetDesktopDisplayMode(index, ByRef w, ByRef h, ByRef freq)
Sub GetPowerInfo(ByRef status, ByRef secs, ByRef pct)
Function EvalJS$(js_code$) 'Only useable in Emscripten
function SystemReturnStdOut$(cmd$) 'new
function OpenURL(url$)
function APIVersion$()
function MessageBox(title$, msg$)
function Runtime$()
function NumCPUs()
