sub GetTerrainPatchAABB( actor, patchX, patchZ, ByRef minX, ByRef minY, ByRef minZ, ByRef maxX, ByRef maxY, ByRef maxZ )
function GetTerrainPatchLOD( actor, patchX, patchZ )
function GetTerrainHeight( actor, patchX, patchZ )
sub GetTerrainCenter( actor, ByRef x, ByRef y, ByRef z )
sub SetTerrainLODDistance( actor, LOD, distance )
sub ScaleTerrainTexture( actor, scale, scale2 )
sub SetTerrainCameraMovementDelta( actor, delta )
sub SetTerrainCameraRotationDelta( actor, delta )
sub SetTerrainPatchLOD( actor, patchX, patchZ, LOD )
