function LoadFont(fnt_file$, font_size)
sub DeleteFont(slot)
Function FontExists(slot)
sub SetFont(slot)
sub DrawText(txt$, x, y)
sub GetTextSize(txt$, byref w, byref h)
function TextWidth(txt$)
function TextHeight(txt$)
