function LoadFont(fnt_file$, size)
sub DeleteFont(slot)
Function FontExists(slot)
sub Font(slot)
sub DrawText(txt$, x, y)
sub RenderText(slot, txt$)
sub GetTextSize(txt$, byref w, byref h)
function GetTextWidth(txt$)
function GetTextHeight(txt$)
