Function CreateTileSet(img_id, tile_w, tile_h)
Sub SetTileAnimationLength(tileset, base_tile, num_frames)
Function GetTileAnimationLength(tileset, base_tile)
Sub SetTileAnimationFrame(tileset, base_tile, anim_frame, tile_frame)
Function GetTileAnimationFrame(tileset, base_tile, anim_frame)
Sub SetTileAnimationSpeed(tileset, base_tile, speed)
Function GetTileAnimationSpeed(tileset, base_tile)
Function CreateTileMap(tileset, widthInTiles, heightInTiles)
Sub SetTileMapSize(tilemap, widthInTiles, heightInTiles)
Sub GetTileMapSize(tilemap, ByRef widthInTiles, ByRef heightInTiles)
Sub SetTile(tilemap, tile, x, y)
Function GetTile(tilemap, x, y)
Sub FillTile(tilemap, tile, x, y, widthInTiles, heightInTiles)
Sub DrawTileMap(tilemap, x, y, w, h, offset_x, offset_y)
