Function AddVehicleWheel( actor, wheel_actor, is_front_wheel )
Sub GetVehicleAxis( actor, ByRef x, ByRef y, ByRef z  )
Sub GetVehicleForwardVector( actor, ByRef x, ByRef y, ByRef z )
Function GetVehicleCurrentSpeed( actor )
Function GetWheelCount( actor )
Sub GetVehicleChassisWorldTransform( actor, t_matrix )
Function GetWheelSteeringValue( actor, wheel )
Sub GetWheelWorldTransform( actor, wheel, t_matrix )
Sub GetWheelConnectionPoint( actor, wheel, ByRef x, ByRef y, ByRef z)
Sub GetWheelDirection( actor, wheel, ByRef x, ByRef y, ByRef z )
Sub GetWheelAxel( actor, wheel, ByRef x, ByRef y, ByRef z )
Function GetWheelSuspensionLength( actor, wheel )
Function GetWheelMaxSuspensionTravel( actor, wheel )
Function GetWheelRadius( actor, wheel )
Function GetWheelSuspensionStiffness( actor, wheel )
Function GetWheelDampingCompression( actor, wheel )
Function GetWheelDampingRelaxation( actor, wheel )
Function GetWheelFrictionSlip( actor, wheel )
Function GetWheelRotation( actor, wheel )
Function GetWheelRotationDelta( actor, wheel )
Function GetWheelRollInfluence( actor, wheel )
Function GetWheelEngineForce( actor, wheel )
Function GetWheelBrake( actor, wheel )
Function WheelIsFront( actor, wheel )
Function GetWheelInverseContactSuspension( actor, wheel )
Function GetWheelSuspensionVelocity( actor, wheel )
Sub ResetVehicleSuspension( actor )
Sub SetWheelSteeringValue( actor, wheel, steering )
Sub ApplyWheelEngineForce( actor, wheel, force )
Sub SetWheelBrake( actor, wheel, brake )
Sub SetVehiclePitchControl( actor, pitch )
Sub SetWheelConnectionPoint( actor, wheel, x, y, z )
Sub SetWheelDirection( actor, wheel, x, y, z )
Sub SetWheelAxel( actor, wheel, x, y, z )
Sub SetWheelSuspensionLength( actor, wheel, s_length )
Sub SetWheelMaxSuspensionTravel( actor, wheel, max_travel )
Sub SetWheelRadius( actor, wheel, radius )
Sub SetWheelSuspensionStiffness( actor, wheel, stiffness )
Sub SetWheelDampingCompression( actor, wheel, dcomp_value )
Sub SetWheelDampingRelaxation( actor, wheel, drel_value )
Sub SetWheelFrictionSlip( actor, wheel, fslip_value )
Sub SetWheelRotation( actor, wheel, rot )
Sub SetWheelRollInfluence( actor, wheel, roll_influence )
Sub SetWheelInverseContactSuspension( actor, wheel, c_value )
Sub SetWheelSuspensionVelocity( actor, wheel, velocity )
Sub SetWheelActorOffsetTransform( actor, wheel, t_matrix )
Sub GetWheelActorOffsetTransform( actor, wheel, t_matrix )
Function GetVehiclePitchControl( actor )
