sub setWaterWindForce( actor,   f)
function  getWaterWindForce( actor)
sub setWaterWaveHeight( actor,   h)
function  getWaterWaveHeight( actor)
sub setWaterWindDirection( actor,   x,   z)
sub getWaterWindDirection( actor,  ByRef  x,  ByRef  z)
sub setWaterColor( actor,  c)
function getWaterColor( actor)
sub setWaterColorBlendFactor( actor,   cbfactor)
function  getWaterColorBlendFactor( actor)
