Function OpenWindow( title$, w, h, fullscreen, vsync )
function OpenWindowEx(title$, x, y, w, h, mode, aa, stencil_buffer, vsync)
sub CloseWindow( )
sub RaiseWindow( )
sub Update()
sub Cls()
sub SetClearColor(c)
sub ShowWindow( )
sub HideWindow( )
sub SetWindowTitle( title$ )
function WindowTitle$( )
sub SetWindowPosition( x, y )
sub GetWindowPosition( byref x, byref y )
sub SetWindowSize( w, h )
sub GetWindowSize( byref w, byref h )
sub SetWindowMinSize( w, h)
sub GetWindowMinSize( byref w, byref h)
sub SetWindowMaxSize( w, h)
sub GetWindowMaxSize( byref w, byref h)
function WindowIsFullscreen()
function WindowIsVisible()
function WindowIsBordered()
function WindowIsResizable()
function WindowIsMinimized()
function WindowIsMaximized()
function WindowHasInputFocus()
function WindowHasMouseFocus()
sub SetWindowFullscreen( flag)
sub MaximizeWindow()
sub MinimizeWindow()
sub SetWindowBordered( flag)
function WindowClip(x, y, w, h)
function WindowExists()
function WindowEvent_Close()
function WindowEvent_Maximize()
function WindowEvent_Minimize()
function FPS()
sub SetWindowIcon( slot)
function WindowEvent_Resize()
sub SetWindowAutoClose( exit_on_close )
sub SetWindowResizable( flag )
function WindowMode(visible, fullscreen, resizable, borderless, highDPI)
function getWindowMode( )
sub RestoreWindow( )
sub GrabInput(flag)
sub SetWindowAlwaysOnTop( flag )
sub SetMouseRelative(flag)
sub SetWindowVSync(flag)
function FlashWindow( flag )
function WindowIsGrabbed( )
Sub PreUpdate( )
Sub SetFPS(fps_val)
